name: Kitsu API Deployment

on: [deployment]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Report Deployment Starting
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/:repo/deployments/:deployment_id/statuses
        repo: ${{ github.repository }}
        deployment_id: ${{ github.event.deployment.id }}
        environment: staging
        state: in_progress
        log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        mediaType: '{"previews": ["flash", "ant-man"]}'
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Connect to Package Registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin"
    - name: Build Docker Image
      run: |
        docker build -t release .
    - name: Tag Docker image
      run: |
        docker tag release docker.pkg.github.com/$GITHUB_REPOSITORY/api:${GITHUB_SHA::8}
        docker tag release docker.pkg.github.com/$GITHUB_REPOSITORY/api:latest
    - name: Push Docker Image
      run: |
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/api:${GITHUB_SHA::8}
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/api:latest

    - name: Report Deployment Success
      uses: octokit/request-action@v2.x
      if: success()
      with:
        route: POST /repos/:repo/deployments/:deployment_id/statuses
        repo: ${{ github.repository }}
        deployment_id: ${{ github.event.deployment.id }}
        environment: staging
        log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        state: success
        mediaType: '{"previews": ["flash", "ant-man"]}'
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
    - name: Report Deployment Failure
      uses: octokit/request-action@v2.x
      if: failure()
      with:
        route: POST /repos/:repo/deployments/:deployment_id/statuses
        repo: ${{ github.repository }}
        deployment_id: ${{ github.event.deployment.id }}
        environment: staging
        log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        environment_url: https://latest.staging.kitsu.io
        state: failure
        mediaType: '{"previews": ["flash", "ant-man"]}'
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
